name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo apt install libglew-dev
        sudo apt install libglfw3-dev
        sudo apt-get install xorg-dev
        sudo apt install -y mesa-common-dev mesa-utils freeglut3-dev
        sudo apt install -y nvidia-340
        sudo apt install libeigen3-dev

    - name: Create Build Environment
      shell: bash
      working-directory: ${{github.workspace}}
      run: mkdir build 

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake ..

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: make 

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ./bin/testunit
